name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - run: yarn --frozen-lockfile --prefer-offline

    - run: yarn all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: ./
      with:
        token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
        retention-weeks: '2'
        containers: |
          fabrique/standup
          fabrique/carnets
          fabrique/hasura
